In [1]:
#array indexing
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1:3]

array([2, 3])

In [5]:
arr_slice =arr[3::4]
arr_slice

array([4, 8])

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [11]:
arr[0,0] #location just like matrix 

np.int64(1)

In [12]:
arr[5,4]

np.int64(30)

In [13]:
arr[0:2,1:3]  

array([[2, 3],
       [7, 8]])

In [14]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
#boolean indexing 
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index = arr %2 ==0 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
slici = arr[bool_index]
slici

array([12, 14, 16, 18, 20])