In [5]:
import numpy as np 

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [10]:
np.array(a) #array automatically converts all into strings 

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]] #list does not support multi dimensional 
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l) #but array does support 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr = np.arange(1,11) # its like loop range it works till n - 1 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# zeros creation
arr = np.zeros((4,8)) # (row,column)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
#linspace 
arr = np.linspace(1,5,3) #linear space dega (start,last no, kitne evenly space mein baate)
arr

array([1., 3., 5.])

In [22]:
#random generate function 
np.random.rand(5)

array([0.64486715, 0.72174749, 0.88869851, 0.75429963, 0.8693688 ])

In [23]:
np.random.randn(4)

array([-0.94477198, -0.98045416, -0.42507221, -1.53154319])

In [25]:
np.random.randint(6) # 6 means 0 se 6 tkk koi bhi random number generate karega 

5

In [26]:
#array attributes 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#array attributes 
arr.shape #attribute ke aage () nahi lagta hain 
arr.size
arr.dtype

dtype('int64')

In [30]:
#array method 
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.min()

np.int64(1)

In [33]:
arr.max()

np.int64(9)

In [34]:
arr.sum()

np.int64(45)

In [36]:
np.sum(arr,axis = 0 )

array([12, 15, 18])

In [37]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std()

np.float64(2.581988897471611)

In [39]:
arr.argmax()

np.int64(8)

In [40]:
arr.argmin()

np.int64(0)

In [42]:
#reshape and resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr = arr.reshape(6,5)


In [47]:
 arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])