In [1]:
#numpy operations 
import numpy as np 

In [6]:
#arithemtic 
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
#size must be same for operation perfomance  

In [8]:
arr2 = a1+a2
arr2

array([ 7,  9, 11, 13, 15])

In [9]:
#all the arithmetic  operation are applicable 

In [10]:
#broadcasting 
l = [1,2,3,4,5]
arr2 = np.array(l)
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr2 +10 #bina loop ke sb mein plus 10 ho jata hain 

array([11, 12, 13, 14, 15])

In [12]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [17]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slicee = a[:4]
slicee =slicee +10
slicee

array([11, 12, 13, 14])

In [20]:
a #change nahi hua original location pe 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a
b=a.copy() #agar copy use nahi karte tb a mein bhi change aata 
b  

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
#matrix operation 
a= np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])

In [52]:
a

array([[1, 2],
       [3, 4]])

In [53]:
b

array([[4, 5],
       [6, 7]])

In [54]:
a * b 

array([[ 4, 10],
       [18, 28]])

In [55]:
np.dot(a,b)

array([[16, 19],
       [36, 43]])

In [56]:
a@b

array([[16, 19],
       [36, 43]])

In [57]:
#transpose 
a.T

array([[1, 3],
       [2, 4]])

In [58]:
# advance array manipulation 
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [59]:
#matrix pahele se stack hota hain toh hm log ushe stack nahi kr skake 
np.vstack((a,b))  #vertical stack 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
np.hstack((a,b)) #horizontal stack 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [62]:
#spiliting
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [66]:
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]